### ISSUE TITLE
The Process isn't the only process

### ISSUE THREAD

**Issue by CaptainEmerson** [barik/survey-chp-ds4se#6]
The process is generally a good one, but there are others. I especially like Active Code Completion (https://www.ics.uci.edu/~tlatoza/papers/graphite-icse12.pdf), which does two things differently:

* Most significantly, it doesn't do interviews.
* Less significantly, it's mostly used for generating qualitative insights, not for confirming some findings quantitatively.

**Comment by barik** [comment]
I was excited about this (it would have made a nice conclusion), but now I'm not entirely sure how to use this paper. It says:

> To help us answer these questions, we conducted a survey of 473 professional developers (Section II). Their responses, along with information gathered from **informal interviews** and code corpus analyses, revealed a number of non-trivial functional requirements for palette interfaces as well as the underlying active code completion architecture (Section III).

While they don't elaborate on the interviews, the story becomes less clean. Thoughts?

**Comment by CaptainEmerson** [comment]
Thanks for the careful reading, I missed that.

That section seems to apply to the generation of the design criteria. I was more interested in the use cases:
> Participants also suggested a large number of use cases,
demonstrating the broad applicability of this technique. We
organize these into several broad categories (Section IV)

Then in that section:
> At the end of the survey, we asked the the participants to
suggest other classes that could benefit from an associated
palette to support our claim that active code completion
is broadly applicable, and to allow us to characterize the
specific scenarios where it may be most useful. A total
of 119 participants made one or more suggestions, which
we classified into several broad categories (we omit a few
of these below due to space constraints). As above, the
number of participants suggesting a palette in each category
is listed in parenthesis. We also include suggestions made
by researchers and developers in private discussions without
including them in the provided counts.

That seems pretty exclusively from the interviews, since the responses were open ended and quantified by response rate in the paper.

**Comment by barik** [comment]
So what should the take away be? Rather than triangulation, that the survey itself can also be used as a way to gather new information/depth about a topic? Though the "private discussions" also muddles that again a little bit.

Basically, one thought I had in the conclusion was to talk about Orpheus, who used an alternate way to face the Sirens. Odysseus isn't the only story. In the same way, I thought this second paper might illustrate an alternative technique.

Hmm. I think I'll tackle some of the other issues first. :)

**Comment by CaptainEmerson** [comment]
The take away is that a survey can be used for generating new ideas and hypothesis. I like the Orpheus idea.

**Comment by barik** [comment]
I sync'd mine with the main ds4se repo. I tried various approaches, unsuccessfully. Putting anything along the lines of an alternate approach in the conclusion just seemed to weaken the ending ("Of course, Odysseus is not the only story. Orpheus, ..... Similarly, surveys can also.... "). Putting it in the middle seemed unnecessary, since we're just giving one perspective on one successful survey process. I don't think we (our our readers) expect that it would be the only one. But feel free to experiment if you like, or feel free to close.

If anything, I think the chapter is probably already too long. But I don't have any hard cut-offs yet on length, so I'll wait and see.

**Comment by barik** [comment]
Yet another option might be to weave it into the psychometric part, since that is already contrasting other ways in which surveys can be used.

**Comment by CaptainEmerson** [comment]
See #15
